version: '3'

services:
  chordpro:
    build: chordpro
    volumes:
      - "${DATA}:/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
#    restart: always
  
  latex: 
    build: latex
    volumes:
      - "${DATA}:/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  # php:
  #   image: php:apache
  #   ports:
  #     - 80
  #   volumes:
  #     - "${DATA}:/var/www/html/data"
  #     - "./html:/var/www/html/"
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - "/etc/timezone:/etc/timezone:ro"

