version: '3'

services:

  web:
    build: web
    restart: always
    ports:
      - "8087:80"
    volumes:
      - ./web/FileLister:/var/www/html
      - "${DATA}:/var/www/html/Liederbuch"
      - /var/run/docker.sock:/var/run/docker.sock
